
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/TOY_DIARY?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
        username: root
        password: 1234
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        devtoos:
            livereload:
            enabled: true
        jpa:
            hibernate:
                naming:
                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl